-- Buyers table for MySQL
CREATE TABLE IF NOT EXISTS `buyers` (
    wallet VARCHAR(50) PRIMARY KEY NOT NULL,
    paid_lamports BIGINT UNSIGNED NOT NULL,
    group_id BIGINT NOT NULL,
    received_percent DOUBLE NOT NULL DEFAULT 0.0,
    received_spl_lamports BIGINT UNSIGNED NOT NULL DEFAULT 0,
    pending_spl_lamports BIGINT UNSIGNED NOT NULL DEFAULT 0,
    error TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES `groups`(id) ON DELETE CASCADE
);